# EternalReports by Oribuin ♥

# Should debug be enabled?
debug: true

# Configure the formatting of the time
date-time-format: 'hh:mm on :dd-m-yyyy'

# Alert Settings
alert-settings:
  sound:
    enabled: true
    # Find all sounds from https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
    sound: 'ENTITY_ARROW_HIT_PLAYER'
    volume: 50

my-sql:
  enabled: false
  hostname: ''
  port: 3310
  database-name: ''
  user-name: ''
  user-password: ''