name: EternalReports
main: xyz.oribuin.eternalreports.EternalReports
version: '@version@'
author: Oribuin
api-version: "1.16"
description: Simple 1.16 Report Plugin made with functionality in mind.
softdepend:
  - PlaceholderAPI
commands:
  report:
    description: Report a user
    usage: /report <user> <reason>
  reports:
    description: Manage reports
    usage: /reports <menu/delete/resolve>
